version: 2.1

orbs:
  node: circleci/node@4.3

jobs:
  test:
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2.1
  run_tests:
    jobs:
      - test
