version: 2.1

orbs:
  node: circleci/node@x.y

jobs:
  test:
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm test

